defaults:
  format: png
  sampler: cftp
  outline: 0.5
  output_size: 10000x10000
  shape: ../shapes/skull.json
  hole_recipe:
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 2, delta: -1}
    - {hole: 2, delta: -1}
    - {hole: 3, delta: 1}
    - {hole: 3, delta: -1}
    - {hole: 3, delta: -1}
    - {hole: 3, delta: -1}
    - {hole: 4, delta: 1}
    - {hole: 4, delta: 1}
    - {hole: 0, delta: 1}
    - {hole: 0, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 2, delta: -1}
    - {hole: 2, delta: -1}
    - {hole: 2, delta: -1}
    - {hole: 3, delta: -1}
    - {hole: 3, delta: -1}
    - {hole: 4, delta: 1}
    - {hole: 4, delta: 1}

designs:
  - name: skull-prints
    schemes: [all]
    sizes: [1]
    variations_per_combo: 1
