defaults:
  format: png
  sampler: cftp
  outline: 0.5
  output_size: 10000x10000
  shape: ../shapes/skull.json
  hole_recipe:
    - {hole: 2, delta: 1}
    - {hole: 2, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 5, delta: 1}
    - {hole: 2, delta: -1}
    - {hole: 2, delta: -1}

designs:
  - name: skull-samples
    schemes: [Skull Bone, Skull Neon, Skull Gothic, Skull Poison, Skull Gilded]
    sizes: [1]
    variations_per_combo: 1

  - name: skull-samples
    schemes: [Skull Muertos]
    sizes: [1]
    outline: 5.0
    variations_per_combo: 1
